const test = require('ava');
const {getPath} = require('../../util');

test('util.getPath', t => {
  t.is(getPath('http://example.com'), './');
  t.is(getPath('http://example.com/'), './');
  t.is(getPath('http://example.com/abc'), './abc');
  t.is(getPath('http://example.com/abc/'), './abc/');
  t.is(getPath('http://example.com/abc/def'), './abc/def');
  t.is(getPath('http://example.com/abc/def/'), './abc/def/');
  t.is(getPath('http://example.com/abc/..'), './');
  t.is(getPath('http://example.com/abc/../'), './');
  t.is(getPath('http://example.com/abc/../def'), './def');
  t.is(getPath('http://example.com/abc/../def/'), './def/');
  t.is(getPath(''), './');
  t.is(getPath('/'), './');
  t.is(getPath('.'), './');
  t.is(getPath('./'), './');
  t.is(getPath('abc'), './abc');
  t.is(getPath('abc/'), './abc/');
  t.is(getPath('/abc'), './abc');
  t.is(getPath('/abc/'), './abc/');
  t.is(getPath('./abc'), './abc');
  t.is(getPath('./abc/'), './abc/');
  t.is(getPath('abc/def'), './abc/def');
  t.is(getPath('abc/def/'), './abc/def/');
  t.is(getPath('/abc/def'), './abc/def');
  t.is(getPath('/abc/def/'), './abc/def/');
  t.is(getPath('./abc/def'), './abc/def');
  t.is(getPath('./abc/def/'), './abc/def/');
  t.falsy(getPath('../abc'));
  t.falsy(getPath('../abc/'));
  t.is(getPath('abc/../def'), './def');
  t.is(getPath('abc/../def/'), './def/');
  t.is(getPath('/abc/../def'), './def');
  t.is(getPath('/abc/../def/'), './def/');
  t.is(getPath('./abc/../def'), './def');
  t.is(getPath('./abc/../def/'), './def/');
});
